name: Build
on: push
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build TypeScript
        run: npm run build
      - name: Install jq
        run: sudo apt-get install -y jq
      - id: getname
        run: |
          echo "NAME=$(cat info.json | jq '.id' | tr -d '"')" >> "$GITHUB_ENV"
          echo "ICON=$(cat info.json | jq '.icon' | tr -d '"')" >> "$GITHUB_ENV"
      - name: Add version to display
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          DISPLAY=$(cat info.json | jq -r '.display')
          jq --arg display "$DISPLAY v$VERSION" '.display = $display' info.json > info.tmp.json
          mv info.tmp.json info.json
      - uses: vimtor/action-zip@v1
        with:
          files: info.json ${{ env.ICON }} main.js
          dest: ${{ env.NAME }}.potext
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }}.potext
          path: "*.potext"
          if-no-files-found: error
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "*.potext"
